### ISSUE TITLE
Mine with Fabulous Panda in a Solo way. Using Own Wallet, instead of pool.

### ISSUE THREAD

**Issue by lordofangels** [fabulouspanda/MacMiner#10]
Hi. I would like to know if it is possible to mine without using a pool adress. Just putting my own wallet in Fabulous Panda. Thank You

**Comment by fabulouspanda** [comment]
If you run Bitcoind and make a .conf file you can solo mine, but MacMiner doesn't have Bitcoind/a wallet built in. There are a bunch of tutorials for solo mining out there.
