### ISSUE TITLE
ClamXav detected Trojan's in 1.5.42

### ISSUE THREAD

**Issue by johnantoni** [fabulouspanda/MacMiner#11]
Hi, downloaded the latest release 1.5.42 and ClamXav reports it's loaded with Trojan's

Downloaded from here:
http://macminer.fabulouspanda.com/macminer/downloads/

<img width="876" alt="screen shot 2017-04-21 at 12 22 07 am" src="https://cloud.githubusercontent.com/assets/15571/25262826/08bee732-2629-11e7-8cac-7d14040dda34.png">

Hopefully it's just false positives but really worrying.

Any ideas? @fabulouspanda

**Comment by johnantoni** [comment]
So then i tried 1.5.40 from http://macminer.fabulouspanda.com/macminer/downloads/

Similar results:

<img width="895" alt="screen shot 2017-04-21 at 12 29 45 am" src="https://cloud.githubusercontent.com/assets/15571/25262965/060fe9b8-262a-11e7-88de-75cbad47fd85.png">

**Comment by johnantoni** [comment]
And the source code from the 1.5.40 release from the github repo, similar

<img width="825" alt="screen shot 2017-04-21 at 12 31 09 am" src="https://cloud.githubusercontent.com/assets/15571/25262983/2649c604-262a-11e7-9c35-9e5b7d1a97ed.png">

Gotta be false positives?

Here's the update log from ClamXav so you can compare definition numbers

<img width="602" alt="screen shot 2017-04-21 at 12 34 53 am" src="https://cloud.githubusercontent.com/assets/15571/25263010/71086d6c-262a-11e7-9cf1-90fab56eba69.png">

**Comment by fabulouspanda** [comment]
I don't think there's anything I can do about that, a lot of coin miners get false positives. The downloads I provide are signed with my Apple Developer ID. This app was pretty popular when mining was so I'm sure Apple would have put a stop to that if I was signing malware!

**Comment by johnantoni** [comment]
You're probably right though I understandably panicked a little when it came up with 14 warnings. 

However I sent the files over to ClamXav themselves to check over on Friday and they came back Monday saying they can't be certain they have Trojan's, they just see a lot of them in mining software.

So you're probably right, sorry about this.
