### ISSUE TITLE
Not really mature

### ISSUE THREAD

**Issue by UnixCro** [fabulouspanda/MacMiner#21]
The error message doesn't come just once and then it's good. No, unfortunately not if you glickt away a window will appear again in 2 seconds. You don't even have to click away - it keeps coming back followed by a system sound. Is there any way to fix that?

![Bildschirmfoto 2021-05-26 um 17 24 21](https://user-images.githubusercontent.com/70098046/119687390-76cc7b80-be47-11eb-93f0-46591cfcdec7.jpg)

Unfortunately, this window comes up every time the app is opened. Unfortunately, it is annoying to keep clicking away.

![Bildschirmfoto 2021-05-26 um 17 26 43](https://user-images.githubusercontent.com/70098046/119687627-a7141a00-be47-11eb-8056-d1fce70aa697.jpg)

**Comment by fabulouspanda** [comment]
The first error usually means you have configured it incorrectly. Free software has ads. Closed because the user is dumb.

**Comment by UnixCro** [comment]
Nevertheless, it is annoying to click on `Uhmm OK` And who is here you would be just like that if it wasn't so annoying. It's not even possible to change anything because every time this damn pop-up window comes up with "Settings changed". It is enough!

These are the error messages. What's wrong with that?

```
Starting… [2021-05-26 17:33:24] /var/folders/0b/5qh2d4h173980pv_gnzyz5yw0000gn/T/AppTranslocation/1811D8C1-5676-42C6-8722-8631339A29A5/d/MacMiner.app/Contents/Resources/bfgminer/bin/bfgminer: -c: JSON decode of file '/Users/user/Library/Application Support/MacMiner/ltcurls.conf' failed
 unable to open /Users/user/Library/Application Support/MacMiner/ltcurls.conf: No such file or directory
```

**Comment by fabulouspanda** [comment]
That means you haven't set up a pool for scrypt which is what you're trying to mine. If you click okay and then stop the miner before it reaches an error again the messages stop. I believe I hot keyed it to cmd-. 

This software hasn't been in development for a long time now.

**Comment by UnixCro** [comment]
Hi,

I've tried everything but it doesn't work. I followed all the instructions.

![Bildschirmfoto 2021-06-08 um 12 09 47](https://user-images.githubusercontent.com/70098046/121167651-6c9c7b00-c852-11eb-8116-8d08ba2980ad.jpg)


```
JSON-RPC problem. Probably couldn't connect. Retrying in 2... 
JSON-RPC problem. Probably couldn't connect. Retrying in 1... 
[33m cl  [35m12:10:09[0m[30m|[34mcl-0    [0m  No work. Pause for 3 s.

[32m  m  [35m12:10:09[0m[30m|[34m        [0m  Waiting for work package...
[101m[1;30m  ✘  [35m12:10:09[0m[30m|[34m        [0m  Failed to submit hashrate.
[101m[1;30m  ✘  [35m12:10:09[0m[30m|[34m        [0m  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8545
[0m
JSON-RPC problem. Probably couldn't connect. Retrying in 2... 
JSON-RPC problem. Probably couldn't connect. Retrying in 1... 
[32m  m  [35m12:10:11[0m[30m|[34m        [0m  Waiting for work package...
[101m[1;30m  ✘  [35m12:10:11[0m[30m|[34m        [0m  Failed to submit hashrate.
[101m[1;30m  ✘  [35m12:10:11[0m[30m|[34m        [0m  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8545
[0m
```

**Comment by fabulouspanda** [comment]
You're setting up a pool for SHA-256 there but you should be for scrypt

**Comment by UnixCro** [comment]
Thanks for your answer. I have changed it now, but unfortunately I still get an error message. I really don't know what I'm doing wrong.

<br>
<img width="493" alt="Bildschirmfoto 2021-06-22 um 09 49 57" src="https://user-images.githubusercontent.com/70098046/122885896-c5ced900-d33f-11eb-8681-c4c092225805.png">
<img width="493" alt="Bildschirmfoto 2021-06-22 um 09 50 05" src="https://user-images.githubusercontent.com/70098046/122885922-cc5d5080-d33f-11eb-81c3-60b13ef992da.png">

**Comment by fabulouspanda** [comment]
Change the intensity setting in the miner prefs, it's out of bounds of the acceptable range for that particular configuration

**Comment by UnixCro** [comment]
I have now set the intensity to 1, but I still get an error message. I think it has something to do with the URL. It says `http://strastratum+tcp://scrypt.eu-west.nicehash.com:3333` although this is exactly what was entered here in my post above `stratum+tcp://scrypt.eu-west.nicehash.com:3333` 

```
Starting… [2021-06-22 12:46:18] Started bfgminer 5.5.0-unknown

 [2021-06-22 12:46:18] Started bfgminer 5.5.0-unknown
 [2021-06-22 12:46:18] Loaded configuration file /Users/home/Library/Application Support/MacMiner/ltcurls.conf

 [2021-06-22 12:46:18] Loaded configuration file /Users/home/Library/Application Support/MacMiner/ltcurls.conf
 [2021-06-22 12:46:18] CL Platform 0 vendor: Apple
 [2021-06-22 12:46:18] CL Platform 0 name: Apple
 [2021-06-22 12:46:18] CL Platform 0 version: OpenCL 1.2 (Dec 21 2020 17:26:36)
 [2021-06-22 12:46:19] Platform 0 devices: 1
 [2021-06-22 12:46:19] 	0	AMD Radeon Pro 570 Compute Engine
 [2021-06-22 12:46:19] Unable to load ati adl library
 [2021-06-22 12:46:19] Probing for an alive pool

 [2021-06-22 12:46:19] Probing for an alive pool
 [2021-06-22 12:46:19] Testing pool http://strastratum+tcp://scrypt.eu-west.nicehash.com:3333
 [2021-06-22 12:46:19] Stratum connect failed to pool 0: Could not resolve host: strastratum+tcp
 [2021-06-22 12:46:19] Pool 0 slow/down or URL or credentials invalid

 [2021-06-22 12:46:19] Pool 0 slow/down or URL or credentials invalid
 [2021-06-22 12:46:20] No servers were found that could be used to get work from.

 [2021-06-22 12:46:20] No servers were found that could be used to get work from.
 [2021-06-22 12:46:20] Please check the details from the list below of the servers you have input

 [2021-06-22 12:46:20] Please check the details from the list below of the servers you have input
 [2021-06-22 12:46:20] Most likely you have input the wrong URL, forgotten to add a port, or have not set up workers

 [2021-06-22 12:46:20] Most likely you have input the wrong URL, forgotten to add a port, or have not set up workers
 [2021-06-22 12:46:20] Pool: 0  URL: http://strastratum+tcp://scrypt.eu-west.nicehash.com:3333  User: 3CAFiAf6rfqFC5H4QfFPG8ZoyBvn8WpnTQ  Password: x

 [2021-06-22 12:46:20] Pool: 0  URL: http://strastratum+tcp://scrypt.eu-west.nicehash.com:3333  User: 3CAFiAf6rfqFC5H4QfFPG8ZoyBvn8WpnTQ  Password: x
No servers could be used! Exiting.

```
Fixed instead of `http://strastratum+tcp://scrypt.eu-west.nicehash.com:3333` this one `stratum+tcp://scrypt.eu-west.nicehash.com:3333` 
<br>

**UPDATE:**

The mining works. The miner has adjusted the algorithm. However, only `Scrypt` worked, no one else. It's a shame that there is no `Etherum` or `KawPow`. Unfortunately, that makes the whole thing unbearable because I can't make a profit that way.

In addition, there is constant talk that the bfgminer has started. However, according to Qullen on the Internet, `bfgminer` should not have any graphics card support at all, so that `bfgminer` cannot mine with a `GPU` at all.

![Bildschirmfoto 2021-06-22 um 13 18 55](https://user-images.githubusercontent.com/70098046/122917048-e1e17300-d35d-11eb-8b94-2e1545761a69.jpg)


Another problem:

NiceHash says that it is mining, but not mining at all:

<img width="375" alt="PNG-Bild" src="https://user-images.githubusercontent.com/70098046/122917430-4d2b4500-d35e-11eb-8edf-61caa971a8d0.png">

Hash speeds are also not visible


<br>
<br>

<h3>Command line tools:</h3>

`~/MacMiner.app/Contents/Resources/cgminer/bin/cgminer` is not recognized by `NiceHash` at all

![Bildschirmfoto 2021-06-22 um 13 46 13](https://user-images.githubusercontent.com/70098046/122919169-37b71a80-d360-11eb-85c6-b6670b56a483.jpg)

<br> 


<h3>Conclusion:</h3>

Unfortunately, the miner is not fully developed.

1. Error messages keep coming that cannot be clicked away with system tones.

2. The miner supports very few algorithms. One looks for something like KawPow or Etherum without success. The algorithms which graphics cards can mine best do not exist.

3. Even if you take Scrypt, which according to my tests is the only algorithm that works with NiceHash, although it shows that it is minted and the graphics card is used, you still don't see any profitability.
You don't see a hash rate, no temperatures, just nothing. It is mining, the graphics cards are used and nothing arrives.

4. There is always a hint that the bfgminer is active when MacMiner mint. According to sources on the Internet, the bfgminer has no graphics card support, only the cgminer.

<br>
Still, I don't want to badmouth the program. I appreciate the work of this program and I wouldn't have come close to getting as far as the developer. I don't even know what mining really is. I just want to throw suggestions for improvement here in the room. I apologize to my first behavior.

**Comment by fabulouspanda** [comment]
You obviously shouldn't have http:// and stratum+tcp:// in the same url address, you can only have one protocol per address. 

It also looks like there's a typo in the one you used:
http://strastratum+tcp://scrypt.eu-west.nicehash.com:3333

"strastratum"

I'll leave the rest for you to figure out on your own

**Comment by UnixCro** [comment]
@fabulouspanda The error was corrected with "UPDATE". Nevertheless, the miner does not work and I wrote something about that above.

<br>

Also, I didn't create this `stratum+tcp://scrypt.eu-west.nicehash.com:3333` , [NiceHash](https://www.nicehash.com/stratum-generator) did it and MacMiner does not issue any error messages
