### ISSUE TITLE
problem noob

### ISSUE THREAD

**Issue by ghost** [fabulouspanda/MacMiner#7]
Hi, vie setup MacMiner. 

Now the software build someone like this : 
20s: 1.23 avg: 3.16 u: 0.00 Mh/s | A:0 R:0+0(none) HW:0/none
20s: 2.15 avg: 3.39 u: 0.00 Mh/s | A:0 R:0+0(none) HW:0/none
20s: 2.73 avg: 3.47 u: 0.00 Mh/s | A:0 R:0+0(none) HW:0/none
20s: 3.06 avg: 3.50 u: 0.00 Mh/s | A:0 R:0+0(none) HW:0/none
20s: 3.11 avg: 3.44 u: 0.00 Mh/s | A:0 R:0+0(none) HW:0/none

But, Accepted and rejected very time is at 0.
It need to buy special ASIC usb key ? I don't understand.

**Comment by fabulouspanda** [comment]
This usually means you're mining too slowly for the difficulty of the pool/network - if you're trying Bitcoin that's definitely the case at those speeds!
