### ISSUE TITLE
VIRUS, TROJAN DETECTED - RISK MAC BITCOINS

### ISSUE THREAD

**Issue by santy2001** [fabulouspanda/MacMiner#8]
The following AntiVirus detect a virus on MAC with the program

Avast	             MacOS:BitCoinMiner-C [Tool]	                       20160605
Ikarus	             PUA.BitCoinMiner	                                       20160605
Kaspersky	     not-a-virus:RiskTool.Java.BitCoinMiner.a	       20160605
NANO-Antivirus    Trojan.Script.BtcMine.drvzgr	                       20160605

**Comment by fabulouspanda** [comment]
None of those names or file names have anything to do with MacMiner, so if a scanner is reliably informing you that you have a Trojan, you got it somewhere else. Does it give you file paths or anything? I wouldn't run Mac OS with Java installed FWIW and MacMiner doesn't use it.
